---
name: Mathbig
title: Mathbig
alternateName: Mathbig
email: marketing@Mathbig.com
address: B404 Noida, 201301
phone: '8750348350'
tagline: Mathbig - Decimals, Fractions and Percentages
description: Mathbig provides Decimals, Fractions and Percentages
baseurl: ''
permalink: /blog/:title
url: https://mathbig.com
siteurl: https://mathbig.com
copyright_text: © 2020 Math-Big
facebook_username: https://www.facebook.com/
linkedin_username: https://www.linkedin.com/in/mathbigcom/
instagram_username: https://www.instagram.com/mathbigcom/
twitter_username: https://twitter.com/mathbigcom
logo: /assets/images/mathbig-logo.svg
paginate: '12'
paginate_path: '/blog/page:num/'
theme: appscms-tools-theme
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
production_google_analytics: 'UA-179965937-12'   
development_google_analytics: ''
disqus:
  shortname: mathbig-1
hero: product_fixed_image
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
getform_id:
mailchimp:
  user-id:
  list-id:
copyright_text: © 2020 Math-Big
company_url: https://math-world.com
google_site_verificatcomn:
bing_site_verificatcomn:
yandex_site_verificatcomn:
naver_site_verificatcomn:
twitter:
  username:
facebook:
  username:
  app_id:
  publisher:
og_image:
social:
  type:
  name:
  links:
analytics:
  provider: false
  google:
    tracking_id:
    anonymize_ip:
timezone:
#after: ruby hello.rb
#page_gen-dirs: false
# page_gen:
#   - data: 'decimal'
#     template: 'decimal'
#     dir: '/all-as-decimal-pages'
#     name_expr: record['value'] + '-' +  record['value2'] + "-as-a-decimal"
#     title_expr: record['value'] + '-' +  record['value2']

#   - data: 'fraction'
#     template: 'fraction'
#     dir: '/all-as-fraction-pages'
#     name_expr: record['value'] + "-as-a-fraction"
#     title_expr: record['value'] + "-as-a-fraction"

#   - data: 'percentage'
#     template: 'percentage'
#     dir: '/all-as-percentage-pages'
#     name_expr: record['value'] + '-' +  record['value2'] + "-as-a-percentage" 
#     title_expr: record['value'] + '-' +  record['value2']
